#!/usr/bin/env python3
"""
Example: Generate a PDF report from HTML

Demonstrates how to use the PDFReportGenerator to create
print-ready PDFs from FirstLight HTML reports.

Usage:
    python examples/generate_pdf_report.py
"""

from pathlib import Path
from core.reporting.pdf import PDFReportGenerator, PDFConfig, PageSize

def main():
    """Generate a sample PDF report."""

    # Sample HTML report
    html_content = """
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="utf-8">
        <title>FirstLight Sample Report</title>
        <style>
            body {
                font-family: sans-serif;
                line-height: 1.6;
                color: #333;
            }
            .fl-cover {
                text-align: center;
                padding: 2in 1in;
            }
            .fl-report-section {
                page-break-before: always;
            }
            .fl-metric-card {
                border: 1px solid #ccc;
                padding: 1rem;
                margin: 1rem 0;
                border-radius: 4px;
            }
        </style>
    </head>
    <body>
        <!-- Cover Page -->
        <div class="fl-cover">
            <h1 style="color: #2B6CB0; font-size: 3rem;">FirstLight Analysis</h1>
            <h2>Geospatial Event Intelligence Platform</h2>
            <p style="margin-top: 2rem;">Sample Report</p>
            <p>Generated: 2026-01-26</p>
        </div>

        <!-- Executive Summary -->
        <div class="fl-report-section">
            <h1>Executive Summary</h1>
            <p>
                This is a sample PDF report generated by the FirstLight reporting system.
                It demonstrates the PDF generation capabilities including automatic
                page breaks, headers, footers, and print-optimized styling.
            </p>

            <div class="fl-metric-card">
                <h3>Key Metrics</h3>
                <ul>
                    <li>Event Type: Flood</li>
                    <li>Affected Area: 3,027 hectares (7,479 acres)</li>
                    <li>Population Impact: 12,000 people</li>
                    <li>Confidence: High (92%)</li>
                </ul>
            </div>
        </div>

        <!-- Analysis Details -->
        <div class="fl-report-section">
            <h1>Analysis Details</h1>
            <h2>Data Sources</h2>
            <p>
                Analysis based on Sentinel-1 SAR imagery acquired on September 28, 2022,
                combined with Sentinel-2 optical imagery for contextual information.
            </p>

            <h2>Methodology</h2>
            <p>
                Change detection algorithm compared pre-event and post-event water extent
                using radiometric thresholding and morphological filtering. Results were
                validated against ground truth data where available.
            </p>
        </div>

        <!-- Recommendations -->
        <div class="fl-report-section">
            <h1>Recommendations</h1>
            <ol>
                <li>Immediate evacuation of affected low-lying areas</li>
                <li>Deploy emergency response teams to high-priority zones</li>
                <li>Establish temporary shelters for displaced residents</li>
                <li>Monitor water levels for potential secondary flooding</li>
            </ol>
        </div>
    </body>
    </html>
    """

    print("FirstLight PDF Report Generator - Example")
    print("=" * 50)

    # Configuration 1: Default (US Letter, 300 DPI)
    print("\n1. Generating report with default settings...")
    config_default = PDFConfig()
    generator_default = PDFReportGenerator(config_default)

    output_default = Path("sample_report_default.pdf")
    try:
        pdf = generator_default.generate(html_content, output_default)
        print(f"   ✓ Generated: {pdf}")
        print(f"   Settings: {config_default.page_size.value}, "
              f"{config_default.orientation}, {config_default.dpi} DPI")
    except RuntimeError as e:
        print(f"   ✗ {e}")
        print("   Install with: pip install weasyprint")

    # Configuration 2: A4 with bleed for professional printing
    print("\n2. Generating report for professional printing...")
    config_print = PDFConfig(
        page_size=PageSize.A4,
        orientation="portrait",
        dpi=300,
        include_bleed=True,
        bleed_mm=3.0
    )
    generator_print = PDFReportGenerator(config_print)

    output_print = Path("sample_report_professional.pdf")
    try:
        pdf = generator_print.generate(html_content, output_print)
        print(f"   ✓ Generated: {pdf}")
        print(f"   Settings: A4, portrait, 300 DPI, 3mm bleed")
    except RuntimeError as e:
        print(f"   ✗ {e}")

    # Configuration 3: Draft quality landscape
    print("\n3. Generating draft report (landscape, 150 DPI)...")
    config_draft = PDFConfig(
        page_size=PageSize.LETTER,
        orientation="landscape",
        dpi=150
    )
    generator_draft = PDFReportGenerator(config_draft)

    output_draft = Path("sample_report_draft.pdf")
    try:
        pdf = generator_draft.generate(html_content, output_draft)
        print(f"   ✓ Generated: {pdf}")
        print(f"   Settings: Letter landscape, 150 DPI (smaller file)")
    except RuntimeError as e:
        print(f"   ✗ {e}")

    # Demonstrate map page generation
    print("\n4. Demonstrating map page HTML generation...")
    map_html = generator_default.generate_map_page(
        map_image_path=Path("flood_extent.png"),
        title="Hurricane Ian Flood Extent",
        caption="Fort Myers, Florida - September 28, 2022"
    )
    print(f"   ✓ Generated map page HTML ({len(map_html)} bytes)")
    print(f"   (This HTML can be embedded in larger reports)")

    print("\n" + "=" * 50)
    print("Example complete!")
    print("\nFor more details, see:")
    print("  core/reporting/pdf/README.md")
    print("  docs/design/CARTOGRAPHIC_SPEC.md")

if __name__ == "__main__":
    main()
