"""
API Models Package.

Exports all Pydantic models for API requests, responses, and errors.
"""

# Error models
from api.models.errors import (
    APIError,
    AuthenticationError,
    AuthorizationError,
    ConflictError,
    DataAcquisitionError,
    ErrorCode,
    ErrorDetail,
    ErrorResponse,
    EventNotFoundError,
    EventProcessingError,
    NotFoundError,
    PipelineExecutionError,
    ProcessingError,
    ProductNotFoundError,
    RateLimitError,
    SchemaValidationError,
    ValidationError,
    api_error_handler,
    generic_exception_handler,
    register_exception_handlers,
)

# Request models
from api.models.requests import (
    BoundingBox,
    CatalogQueryParams,
    DataConstraints,
    DataTypeCategory,
    EventMetadata,
    EventPriority,
    EventQueryParams,
    EventSortField,
    Geometry,
    GeometryType,
    IntentSpec,
    Polarization,
    ProductDownloadParams,
    ProductQueryParams,
    SortOrder,
    SpatialSpec,
    TemporalExtent,
    EventSubmitRequest,
)

# Response models
from api.models.responses import (
    AlgorithmInfo,
    CatalogAlgorithmsResponse,
    CatalogEventTypesResponse,
    CatalogSourcesResponse,
    DataSourceInfo,
    EventResponse,
    EventStatus,
    EventSummary,
    EventTypeInfo,
    HealthCheckComponent,
    HealthResponse,
    LivenessResponse,
    PaginatedResponse,
    PaginationMeta,
    PipelineStepProgress,
    ProductFormat,
    ProductMetadata,
    ProductQuality,
    ProductResponse,
    ProductStatus,
    ProgressResponse,
    QualityFlag,
    ReadinessResponse,
    ResolvedIntent,
    SpatialInfo,
    StatusResponse,
)

__all__ = [
    # Errors
    "APIError",
    "AuthenticationError",
    "AuthorizationError",
    "ConflictError",
    "DataAcquisitionError",
    "ErrorCode",
    "ErrorDetail",
    "ErrorResponse",
    "EventNotFoundError",
    "EventProcessingError",
    "NotFoundError",
    "PipelineExecutionError",
    "ProcessingError",
    "ProductNotFoundError",
    "RateLimitError",
    "SchemaValidationError",
    "ValidationError",
    "api_error_handler",
    "generic_exception_handler",
    "register_exception_handlers",
    # Requests
    "BoundingBox",
    "CatalogQueryParams",
    "DataConstraints",
    "DataTypeCategory",
    "EventMetadata",
    "EventPriority",
    "EventQueryParams",
    "EventSortField",
    "EventSubmitRequest",
    "Geometry",
    "GeometryType",
    "IntentSpec",
    "Polarization",
    "ProductDownloadParams",
    "ProductQueryParams",
    "SortOrder",
    "SpatialSpec",
    "TemporalExtent",
    # Responses
    "AlgorithmInfo",
    "CatalogAlgorithmsResponse",
    "CatalogEventTypesResponse",
    "CatalogSourcesResponse",
    "DataSourceInfo",
    "EventResponse",
    "EventStatus",
    "EventSummary",
    "EventTypeInfo",
    "HealthCheckComponent",
    "HealthResponse",
    "LivenessResponse",
    "PaginatedResponse",
    "PaginationMeta",
    "PipelineStepProgress",
    "ProductFormat",
    "ProductMetadata",
    "ProductQuality",
    "ProductResponse",
    "ProductStatus",
    "ProgressResponse",
    "QualityFlag",
    "ReadinessResponse",
    "ResolvedIntent",
    "SpatialInfo",
    "StatusResponse",
]
